from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel

CURRENT_AGENT_MODEL = "__CURRENT_AGENT_MODEL__"
CURRENT_AGENT_ADAPTER = "__CURRENT_AGENT_ADAPTER__"


class AgentEvalConfig(BaseModel):
    adapter: str = "openai"
    model: str
    mode: Literal["policy", "agent"] = "agent"
    scenarios: str = "scenarios/mvp"
    out: str = "runs/agent_eval"
    file_path: str | None = None
    base_url: str | None = None
    temperature: float = 0.0
    max_output_tokens: int = 1200
    timeout_seconds: int = 60
    max_retries: int = 1
    label: str | None = None
    notes: str | None = None


def load_agent_eval_config(path: str | Path) -> AgentEvalConfig:
    config_path = Path(path)
    suffix = config_path.suffix.lower()
    raw_text = config_path.read_text(encoding="utf-8")
    if suffix in {".yaml", ".yml"}:
        payload = yaml.safe_load(raw_text) or {}
    elif suffix == ".json":
        payload = json.loads(raw_text)
    else:
        raise ValueError("Agent eval config must be .yaml, .yml, or .json")
    return AgentEvalConfig.model_validate(payload)


def write_agent_eval_template(path: str | Path) -> Path:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    template = AgentEvalConfig(
        adapter=CURRENT_AGENT_ADAPTER,
        model=CURRENT_AGENT_MODEL,
        mode="agent",
        scenarios="scenarios/mvp",
        out="runs/self_eval_current_agent",
        temperature=0.0,
        max_output_tokens=1200,
        timeout_seconds=60,
        max_retries=1,
        notes=(
            "If your coding agent can infer its current provider/model, replace the placeholders automatically. "
            "Otherwise set LEXCAPITAL_AGENT_ADAPTER and LEXCAPITAL_AGENT_MODEL before running self-eval."
        ),
    )
    out_path.write_text(yaml.safe_dump(template.model_dump(), sort_keys=False), encoding="utf-8")
    return out_path


def save_agent_eval_request(config: AgentEvalConfig, out_dir: str | Path) -> Path:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    request_path = out / "agent_eval_request.json"
    request_path.write_text(json.dumps(config.model_dump(), indent=2), encoding="utf-8")
    return request_path


def _first_env(*names: str) -> str | None:
    for name in names:
        value = os.getenv(name)
        if value:
            return value
    return None


def infer_agent_adapter(
    adapter: str | None = None,
    *,
    base_url: str | None = None,
) -> str:
    if adapter:
        return adapter
    env_adapter = _first_env(
        "LEXCAPITAL_AGENT_ADAPTER",
        "CURRENT_AGENT_ADAPTER",
        "BENCHMARK_AGENT_ADAPTER",
    )
    if env_adapter:
        return env_adapter
    if base_url or _first_env("LEXCAPITAL_LOCAL_BASE_URL", "OPENAI_BASE_URL"):
        return "local-http"
    if os.getenv("OPENAI_API_KEY"):
        return "openai"
    return CURRENT_AGENT_ADAPTER


def infer_agent_model(model: str | None = None) -> str:
    if model:
        return model
    env_model = _first_env(
        "LEXCAPITAL_AGENT_MODEL",
        "CURRENT_AGENT_MODEL",
        "CLAUDE_CODE_MODEL",
        "ANTHROPIC_MODEL",
        "OPENAI_MODEL",
        "MODEL",
        "CODEX_MODEL",
    )
    if env_model:
        return env_model
    return CURRENT_AGENT_MODEL


def default_self_eval_config(
    *,
    adapter: str | None = None,
    model: str | None = None,
    mode: Literal["policy", "agent"] = "agent",
    scenarios: str = "scenarios/mvp",
    out: str | None = None,
    file_path: str | None = None,
    base_url: str | None = None,
    temperature: float = 0.0,
    max_output_tokens: int = 1200,
    timeout_seconds: int = 60,
    max_retries: int = 1,
) -> AgentEvalConfig:
    resolved_adapter = infer_agent_adapter(adapter, base_url=base_url)
    resolved_model = infer_agent_model(model)
    if out is None:
        safe_model = re.sub(r"[^a-zA-Z0-9._-]+", "_", resolved_model) or "current_agent"
        out = f"runs/self_eval_{safe_model}"
    return AgentEvalConfig(
        adapter=resolved_adapter,
        model=resolved_model,
        mode=mode,
        scenarios=scenarios,
        out=out,
        file_path=file_path,
        base_url=base_url,
        temperature=temperature,
        max_output_tokens=max_output_tokens,
        timeout_seconds=timeout_seconds,
        max_retries=max_retries,
        notes="Generated by self-eval helper.",
    )


def config_has_placeholders(config: AgentEvalConfig) -> bool:
    return config.adapter == CURRENT_AGENT_ADAPTER or config.model == CURRENT_AGENT_MODEL
